language: python
notifications:
  email:
    recipients:
      - d.zlatanidis@gmail.com
    on_success: never
    on_failure: always
python:
  - "3.7"
script:
  - pip install -r requirements.txt
# python -m pytest tests/